export interface ResolutionConsumption {
    value: number;
    unit: string;
}

export interface ResolutionItem {
    frequency: string;
    weeklyConsumption: ResolutionConsumption;
    monthlyConsumption: ResolutionConsumption; // This is "Consumo em 4"
}

const parseConsumption = (text: string | null): ResolutionConsumption => {
    if (!text || text.trim() === '-') return { value: 0, unit: '' };
    const parts = text.trim().split(' ');
    const unit = parts.pop() || '';
    const valueStr = parts.join('');
    const value = parseFloat(valueStr.replace(/\./g, '').replace(',', '.')) || 0;
    return { value, unit };
}

// Dados extraídos da planilha fornecida
export const resolutionData: Record<string, ResolutionItem> = {
    'ABACATE': { frequency: '1x/semana', weeklyConsumption: parseConsumption('1.008 g'), monthlyConsumption: parseConsumption('4.032 g') },
    'ABACAXI': { frequency: '1x/semana', weeklyConsumption: parseConsumption('1.008 g'), monthlyConsumption: parseConsumption('4.032 g') },
    'ABÓBORA JAPONESA': { frequency: '1x/semana', weeklyConsumption: parseConsumption('676 g'), monthlyConsumption: parseConsumption('2.704 g') },
    'ABOBRINHA BRASILEIRA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('1.072 g'), monthlyConsumption: parseConsumption('4.288 g') },
    'ACELGA ALONGADA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('400 g'), monthlyConsumption: parseConsumption('1.600 g') },
    'ACELGA COZIDA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('960 g'), monthlyConsumption: parseConsumption('3.840 g') },
    'ACHOCOLATADO EM PÓ': { frequency: '2x/semana', weeklyConsumption: parseConsumption('240 g'), monthlyConsumption: parseConsumption('960 g') },
    'AÇÚCAR REFINADO': { frequency: '-', weeklyConsumption: parseConsumption('1.236 g'), monthlyConsumption: parseConsumption('4.944 g') },
    'AÇÚCAR CRISTAL': { frequency: '2x/dia', weeklyConsumption: parseConsumption('618 g'), monthlyConsumption: parseConsumption('2.472 g') },
    'ADOÇANTE EM SACHÊ': { frequency: '3x/dia', weeklyConsumption: parseConsumption('8,2 g'), monthlyConsumption: parseConsumption('32,8 g') },
    'ADOÇANTE LÍQUIDO': { frequency: '3x/dia', weeklyConsumption: parseConsumption('15 ml'), monthlyConsumption: parseConsumption('60 ml') },
    'AGRIÃO': { frequency: '3x/semana', weeklyConsumption: parseConsumption('840 g'), monthlyConsumption: parseConsumption('3.360 g') },
    'ALFACE CRESPA': { frequency: '3x/semana', weeklyConsumption: parseConsumption('600 g'), monthlyConsumption: parseConsumption('2.400 g') },
    'ALFACE LISA': { frequency: '3x/semana', weeklyConsumption: parseConsumption('600 g'), monthlyConsumption: parseConsumption('2.400 g') },
    'ALMÔNDEGA BOVINA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('1.000 g'), monthlyConsumption: parseConsumption('4.000 g') },
    'AMIDO BASE: DE MILHO': { frequency: '2x/semana', weeklyConsumption: parseConsumption('10,2 g'), monthlyConsumption: parseConsumption('40,8 g') },
    'AMIDO DE ARROZ': { frequency: '-', weeklyConsumption: parseConsumption('124 g'), monthlyConsumption: parseConsumption('496 g') },
    'AMIDO DE MILHO': { frequency: '-', weeklyConsumption: parseConsumption('124 g'), monthlyConsumption: parseConsumption('496 g') },
    'ARROZ BENEFICIADO TIPO: AGULHINHA': { frequency: '2x/dia', weeklyConsumption: parseConsumption('7.500 g'), monthlyConsumption: parseConsumption('30.000 g') },
    'ARROZ PARBOILIZADO': { frequency: '2x/dia', weeklyConsumption: parseConsumption('7.500 g'), monthlyConsumption: parseConsumption('30.000 g') },
    'AVEIA EM FLOCOS': { frequency: '-', weeklyConsumption: parseConsumption('80 g'), monthlyConsumption: parseConsumption('320 g') },
    'AVEIA LAMINADA': { frequency: '1x/semana', weeklyConsumption: parseConsumption('23 g'), monthlyConsumption: parseConsumption('92 g') },
    'AZEITE EXTRA VIRGEM': { frequency: '-', weeklyConsumption: parseConsumption('15 ml'), monthlyConsumption: parseConsumption('60 ml') },
    'BANANA NANICA': { frequency: '7x/semana', weeklyConsumption: parseConsumption('28 unid.'), monthlyConsumption: parseConsumption('112 unid.') },
    'BANANA PRATA DE PRIMEIRA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('2 unid.'), monthlyConsumption: parseConsumption('8 unid.') },
    'BEBIDA LÁCTEA (VÁRIOS SABORES)': { frequency: '2x/semana', weeklyConsumption: parseConsumption('1.600 ml'), monthlyConsumption: parseConsumption('6.400 ml') },
    'BERINJELA': { frequency: '1x/semana', weeklyConsumption: parseConsumption('456 g'), monthlyConsumption: parseConsumption('1.824 g') },
    'BETERRABA COZIDA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('1.360 g'), monthlyConsumption: parseConsumption('5.440 g') },
    'BETERRABA CRUA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('400 g'), monthlyConsumption: parseConsumption('1.600 g') },
    'BISCOITO APRESENTAÇÃO: REDONDO, SABOR: MAIZENA': { frequency: '4x/semana', weeklyConsumption: parseConsumption('640 g'), monthlyConsumption: parseConsumption('2.560 g') },
    'BOLACHA DOCE (MAISENA/MARIA)': { frequency: '2x/semana', weeklyConsumption: parseConsumption('41 g'), monthlyConsumption: parseConsumption('164 g') },
    'BOLACHA SALGADA (ÁGUA E SAL/CREAM CRACKER)': { frequency: '4x/semana', weeklyConsumption: parseConsumption('640 g'), monthlyConsumption: parseConsumption('2.560 g') },
    'BOLACHA SEM SAL (ÁGUA)': { frequency: '3x/semana', weeklyConsumption: parseConsumption('41 g'), monthlyConsumption: parseConsumption('164 g') },
    'BRÓCOLIS': { frequency: '1x/semana', weeklyConsumption: parseConsumption('720 g'), monthlyConsumption: parseConsumption('2.880 g') },
    'CAFÉ APRESENTAÇÃO: TORRADO MOÍDO': { frequency: '3x/dia', weeklyConsumption: parseConsumption('927 g'), monthlyConsumption: parseConsumption('3.708 g') },
    'CAFÉ TORRADO/MOÍDO': { frequency: '3x/dia', weeklyConsumption: parseConsumption('927 g'), monthlyConsumption: parseConsumption('3.708 g') },
    'CANELA EM PÓ': { frequency: '-', weeklyConsumption: parseConsumption('1 g'), monthlyConsumption: parseConsumption('4 g') },
    'CANELA EM RAMA': { frequency: '-', weeklyConsumption: parseConsumption('1 g'), monthlyConsumption: parseConsumption('4 g') },
    'CAQUI': { frequency: '1x/semana', weeklyConsumption: parseConsumption('4 unid.'), monthlyConsumption: parseConsumption('16 unid.') },
    'CARÁ': { frequency: '1x/quinzena', weeklyConsumption: parseConsumption('270 g'), monthlyConsumption: parseConsumption('1.080 g') },
    'CARNE BOVINA ACÉM': { frequency: '6x/semana', weeklyConsumption: parseConsumption('3.240 g'), monthlyConsumption: parseConsumption('12.960 g') },
    'CARNE BOVINA COXÃO MOLE': { frequency: '6x/semana', weeklyConsumption: parseConsumption('3.240 g'), monthlyConsumption: parseConsumption('12.960 g') },
    'CARNE BOVINA IN NATURA TIPO DE CORTE: PALETA': { frequency: '6x/semana', weeklyConsumption: parseConsumption('3.240 g'), monthlyConsumption: parseConsumption('12.960 g') },
    'CARNE BOVINA MÚSCULO': { frequency: '6x/semana', weeklyConsumption: parseConsumption('3.240 g'), monthlyConsumption: parseConsumption('12.960 g') },
    'CARNE BOVINA PATINHO': { frequency: '6x/semana', weeklyConsumption: parseConsumption('3.240 g'), monthlyConsumption: parseConsumption('12.960 g') },
    'CARNE BOVINA PEITO': { frequency: '6x/semana', weeklyConsumption: parseConsumption('3.240 g'), monthlyConsumption: parseConsumption('12.960 g') },
    'CARNE BOVINA PESCOÇO': { frequency: '6x/semana', weeklyConsumption: parseConsumption('3.240 g'), monthlyConsumption: parseConsumption('12.960 g') },
    'CARNE BOVINA CUPIM': { frequency: '6x/semana', weeklyConsumption: parseConsumption('3.240 g'), monthlyConsumption: parseConsumption('12.960 g') },
    'CARNE DE AVE IN NATURA: PEITO DE FRANGO': { frequency: '2x/semana', weeklyConsumption: parseConsumption('1.280 g'), monthlyConsumption: parseConsumption('5.120 g') },
    'CARNE SALGADA TIPO DE CORTE: TOUCINHO': { frequency: '-', weeklyConsumption: parseConsumption('60 g'), monthlyConsumption: parseConsumption('240 g') },
    'CARNE SUÍNA BISTECA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('1.120 g'), monthlyConsumption: parseConsumption('4.480 g') },
    'CARNE SUÍNA COPA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('1.120 g'), monthlyConsumption: parseConsumption('4.480 g') },
    'CARNE SUÍNA LOMBO': { frequency: '2x/semana', weeklyConsumption: parseConsumption('1.120 g'), monthlyConsumption: parseConsumption('4.480 g') },
    'CARNE SUINA PERNIL': { frequency: '2x/semana', weeklyConsumption: parseConsumption('1.120 g'), monthlyConsumption: parseConsumption('4.480 g') },
    'KETCHUP (CONDIMENTO PREPARADO)': { frequency: '-', weeklyConsumption: parseConsumption('31 g'), monthlyConsumption: parseConsumption('124 g') },
    'CEBOLINHA (CHEIRO VERDE)': { frequency: '-', weeklyConsumption: parseConsumption('83 g'), monthlyConsumption: parseConsumption('332 g') },
    'CENOURA COZIDA': { frequency: '3x/semana', weeklyConsumption: parseConsumption('1.440 g'), monthlyConsumption: parseConsumption('5.760 g') },
    'CENOURA CRUA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('400 g'), monthlyConsumption: parseConsumption('1.600 g') },
    'CHÁ (CAMOMILA, ERVA CIDREIRA, HORTELÃ, ERVA-DOCE)': { frequency: '-', weeklyConsumption: parseConsumption('8 g'), monthlyConsumption: parseConsumption('32 g') },
    'CHÁ CAMOMILA': { frequency: '1x/semana', weeklyConsumption: parseConsumption('40 g'), monthlyConsumption: parseConsumption('160 g') },
    'CHÁ DE ERVA MATE': { frequency: '-', weeklyConsumption: parseConsumption('33 g'), monthlyConsumption: parseConsumption('132 g') },
    'CHÁ ERVA-DOCE': { frequency: '1x/semana', weeklyConsumption: parseConsumption('40 g'), monthlyConsumption: parseConsumption('160 g') },
    'CHÁ HORTELÃ': { frequency: '1x/semana', weeklyConsumption: parseConsumption('40 g'), monthlyConsumption: parseConsumption('160 g') },
    'CHÁ MATE': { frequency: '1x/semana', weeklyConsumption: parseConsumption('40 g'), monthlyConsumption: parseConsumption('160 g') },
    'CHÁ PRETO': { frequency: '1x/semana', weeklyConsumption: parseConsumption('40 g'), monthlyConsumption: parseConsumption('160 g') },
    'CHARQUE': { frequency: '1x/semana', weeklyConsumption: parseConsumption('540 g'), monthlyConsumption: parseConsumption('2.160 g') },
    'CHARQUE (PREPARO)': { frequency: '1x/semana', weeklyConsumption: parseConsumption('240 g'), monthlyConsumption: parseConsumption('960 g') },
    'CHOCOLATE EM PÓ SOLÚVEL': { frequency: '-', weeklyConsumption: parseConsumption('93 g'), monthlyConsumption: parseConsumption('372 g') },
    'CHOCOLATE EM PÓ SOLÚVEL SEM AÇÚCAR': { frequency: 'Preparo', weeklyConsumption: parseConsumption('93 g'), monthlyConsumption: parseConsumption('372 g') },
    'CHUCHU': { frequency: '2x/semana', weeklyConsumption: parseConsumption('1.200 g'), monthlyConsumption: parseConsumption('4.800 g') },
    'CÔCO RALADO': { frequency: '-', weeklyConsumption: parseConsumption('10 g'), monthlyConsumption: parseConsumption('40 g') },
    'COLORÍFICO EM PÓ': { frequency: '-', weeklyConsumption: parseConsumption('3 g'), monthlyConsumption: parseConsumption('12 g') },
    'COMINHO MOÍDO': { frequency: '-', weeklyConsumption: parseConsumption('2 g'), monthlyConsumption: parseConsumption('8 g') },
    'CONDIMENTO TIPO: ORÉGANO': { frequency: '-', weeklyConsumption: parseConsumption('5 g'), monthlyConsumption: parseConsumption('20 g') },
    'CONDIMENTO TIPO: PIMENTA DO REINO': { frequency: '-', weeklyConsumption: parseConsumption('10 g'), monthlyConsumption: parseConsumption('40 g') },
    'COSTELA SUÍNA SALGADA': { frequency: '1x/semana', weeklyConsumption: parseConsumption('204 g'), monthlyConsumption: parseConsumption('816 g') },
    'COUVE MANTEIGA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('400 g'), monthlyConsumption: parseConsumption('1.600 g') },
    'COUVE MANTEIGA COZIDA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('880 g'), monthlyConsumption: parseConsumption('3.520 g') },
    'COUVE-FLOR': { frequency: '1x/semana', weeklyConsumption: parseConsumption('640 g'), monthlyConsumption: parseConsumption('2.560 g') },
    'COXA E SOBRECOXA': { frequency: '4x/semana', weeklyConsumption: parseConsumption('4.128 g'), monthlyConsumption: parseConsumption('16.512 g') },
    'COXÃO DURO PEÇA INTEIRA RESFRIADA': { frequency: '6x/semana', weeklyConsumption: parseConsumption('3.240 g'), monthlyConsumption: parseConsumption('12.960 g') },
    'CRAVO DA ÍNDIA': { frequency: '-', weeklyConsumption: parseConsumption('1 g'), monthlyConsumption: parseConsumption('4 g') },
    'CREME DE CEBOLA EM PÓ': { frequency: '-', weeklyConsumption: parseConsumption('5 g'), monthlyConsumption: parseConsumption('20 g') },
    'CREME DE LEITE': { frequency: '-', weeklyConsumption: parseConsumption('11 g'), monthlyConsumption: parseConsumption('44 g') },
    'DOBRADINHA BOVINA': { frequency: '1x/quinzena', weeklyConsumption: parseConsumption('248 g'), monthlyConsumption: parseConsumption('992 g') },
    'DOCE DE LEITE': { frequency: '1x/quinzena', weeklyConsumption: parseConsumption('80 g'), monthlyConsumption: parseConsumption('320 g') },
    'DOCE DE LEITE EM PASTA': { frequency: '-', weeklyConsumption: parseConsumption('40 g'), monthlyConsumption: parseConsumption('160 g') },
    'DOCE DE LEITE, TIPO: TRADICIONAL': { frequency: '1x/quinzena', weeklyConsumption: parseConsumption('80 g'), monthlyConsumption: parseConsumption('320 g') },
    'DOCE NÃO CONFEITADO TIPO: CREMOSO, SABOR: ABÓBORA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('320 g cada'), monthlyConsumption: parseConsumption('1.280 g cada') },
    'EMBUTIDO TIPO: LINGUIÇA CALABRESA': { frequency: '1x/semana', weeklyConsumption: parseConsumption('560 g'), monthlyConsumption: parseConsumption('2.240 g') },
    'EMBUTIDO TIPO: LINGUIÇA TOSCANA': { frequency: '1x/semana', weeklyConsumption: parseConsumption('720 g'), monthlyConsumption: parseConsumption('2.880 g') },
    'ERVILHA VERDE EM CONSERVA': { frequency: '-', weeklyConsumption: parseConsumption('40 g'), monthlyConsumption: parseConsumption('160 g') },
    'ESCAROLA': { frequency: '3x/semana', weeklyConsumption: parseConsumption('600 g'), monthlyConsumption: parseConsumption('2.400 g') },
    'ESCAROLA COZIDA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('880 g'), monthlyConsumption: parseConsumption('3.520 g') },
    'ESPINAFRE': { frequency: '1x/semana', weeklyConsumption: parseConsumption('640 g'), monthlyConsumption: parseConsumption('2.560 g') },
    'ESSÊNCIA ARTIFICIAL DE BAUNILHA': { frequency: '-', weeklyConsumption: parseConsumption('5 ml'), monthlyConsumption: parseConsumption('20 ml') },
    'FARINHA DE MANDIOCA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('320 g'), monthlyConsumption: parseConsumption('1.280 g') },
    'FARINHA DE MILHO AMARELA': { frequency: '-', weeklyConsumption: parseConsumption('40 g'), monthlyConsumption: parseConsumption('160 g') },
    'FARINHA DE MILHO GRÃO: AMARELO, TIPO: FUBÁ': { frequency: '1x/semana', weeklyConsumption: parseConsumption('160 g'), monthlyConsumption: parseConsumption('640 g') },
    'FARINHA DE ROSCA': { frequency: '-', weeklyConsumption: parseConsumption('124 g'), monthlyConsumption: parseConsumption('496 g') },
    'FARINHA DE TRIGO COMUM/ESPECIAL': { frequency: '-', weeklyConsumption: parseConsumption('312 g'), monthlyConsumption: parseConsumption('1.248 g') },
    'FARINHA DE TRIGO GRUPO: DOMÉSTICO, TIPO: TIPO 1': { frequency: 'Panificação', weeklyConsumption: parseConsumption('3.120 g'), monthlyConsumption: parseConsumption('12.480 g') },
    'FEIJÃO BRANCO': { frequency: '1x/quinzena', weeklyConsumption: parseConsumption('104 g'), monthlyConsumption: parseConsumption('416 g') },
    'FERMENTO BIOLÓGICO': { frequency: '-', weeklyConsumption: parseConsumption('1 g'), monthlyConsumption: parseConsumption('4 g') },
    'FERMENTO QUÍMICO': { frequency: '-', weeklyConsumption: parseConsumption('2 g'), monthlyConsumption: parseConsumption('8 g') },
    'FERMENTO TIPO: BIOLÓGICO SECO': { frequency: '2x/dia', weeklyConsumption: parseConsumption('1 g'), monthlyConsumption: parseConsumption('4 g') },
    'FERMENTO TIPO: QUÍMICO': { frequency: '2x/dia', weeklyConsumption: parseConsumption('3 g'), monthlyConsumption: parseConsumption('12 g') },
    'FÍGADO BOVINO': { frequency: '1x/quinzena', weeklyConsumption: parseConsumption('260 g'), monthlyConsumption: parseConsumption('1.040 g') },
    'FRANGO ALMÔNDEGA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('1.000 g'), monthlyConsumption: parseConsumption('4.000 g') },
    'FRANGO EMPANADO': { frequency: '2x/semana', weeklyConsumption: parseConsumption('960 g'), monthlyConsumption: parseConsumption('3.840 g') },
    'FRANGO INTEIRO (SEM PÉ E CABEÇA)': { frequency: '4x/semana', weeklyConsumption: parseConsumption('4.128 g'), monthlyConsumption: parseConsumption('16.512 g') },
    'FRANGO PEITO SEM OSSO/SEM PELE (FILÉ, SASSAMI, CUBOS)': { frequency: '2x/semana', weeklyConsumption: parseConsumption('960 g'), monthlyConsumption: parseConsumption('3.840 g') },
    'FUBÁ DE MILHO': { frequency: '3x/semana', weeklyConsumption: parseConsumption('480 g'), monthlyConsumption: parseConsumption('1.920 g') },
    'GELÉIA DE FRUTAS DIETÉTICA (SABORES DIVERSOS)': { frequency: '2x/semana', weeklyConsumption: parseConsumption('15 g'), monthlyConsumption: parseConsumption('60 g') },
    'GOIABA VERMELHA': { frequency: '1x/semana', weeklyConsumption: parseConsumption('4 unid.'), monthlyConsumption: parseConsumption('16 unid.') },
    'GORDURA VEGETAL TIPO: MARGARINA': { frequency: '2x/dia', weeklyConsumption: parseConsumption('5,1 g'), monthlyConsumption: parseConsumption('20,4 g') },
    'GRÃO DE BICO': { frequency: '-', weeklyConsumption: parseConsumption('62 g'), monthlyConsumption: parseConsumption('248 g') },
    'HAMBÚRGUER BOVINO': { frequency: '2x/semana', weeklyConsumption: parseConsumption('960 g'), monthlyConsumption: parseConsumption('3.840 g') },
    'HORTELÃ': { frequency: '-', weeklyConsumption: parseConsumption('5 g'), monthlyConsumption: parseConsumption('20 g') },
    'LARANJA LIMA': { frequency: '6x/semana', weeklyConsumption: parseConsumption('1 unid.'), monthlyConsumption: parseConsumption('24 unid.') },
    'LARANJA PERA': { frequency: '6x/semana', weeklyConsumption: parseConsumption('24 unid.'), monthlyConsumption: parseConsumption('96 unid.') },
    'LEGUME EM CONSERVA TIPO: MILHO VERDE': { frequency: '-', weeklyConsumption: parseConsumption('40 g'), monthlyConsumption: parseConsumption('160 g') },
    'LEGUMINOSA VARIEDADE: FEIJÃO CARIOCA': { frequency: '2x/dia', weeklyConsumption: parseConsumption('3.120 g'), monthlyConsumption: parseConsumption('12.480 g') },
    'LEGUMINOSA VARIEDADE: FEIJÃO PRETO': { frequency: '1x/semana', weeklyConsumption: parseConsumption('208 g'), monthlyConsumption: parseConsumption('832 g') },
    'LEITE CONDENSADO': { frequency: '-', weeklyConsumption: parseConsumption('11 ml'), monthlyConsumption: parseConsumption('44 ml') },
    'LEITE CONDENSADO TIPO: INTEGRAL': { frequency: '1x/dia', weeklyConsumption: parseConsumption('1.050 g'), monthlyConsumption: parseConsumption('4.200 g') },
    'LEITE DE VACA IN NATURA TIPO C': { frequency: '-', weeklyConsumption: parseConsumption('132 ml'), monthlyConsumption: parseConsumption('528 ml') },
    'LEITE DE VACA UHT INTEGRAL': { frequency: '-', weeklyConsumption: parseConsumption('132 ml'), monthlyConsumption: parseConsumption('528 ml') },
    'LEITE EM PÓ DESNATADO': { frequency: '2x/dia', weeklyConsumption: parseConsumption('32 g'), monthlyConsumption: parseConsumption('128 g') },
    'LEITE FLUIDO ORIGEM: DE VACA, TIPO: A': { frequency: '2x/dia', weeklyConsumption: parseConsumption('12 L'), monthlyConsumption: parseConsumption('48 L') },
    'LEITE IN NATURA DESNATADO': { frequency: '2x/dia', weeklyConsumption: parseConsumption('252 ml'), monthlyConsumption: parseConsumption('1.008 ml') },
    'LEITE PASTEURIZADO': { frequency: '2x/dia', weeklyConsumption: parseConsumption('12 L'), monthlyConsumption: parseConsumption('48 L') },
    'LENTILHA': { frequency: '2x/quinzena', weeklyConsumption: parseConsumption('200 g'), monthlyConsumption: parseConsumption('800 g') },
    'LIMÃO TAHITI': { frequency: '-', weeklyConsumption: parseConsumption('4 g'), monthlyConsumption: parseConsumption('16 g') },
    'LIMÃO TAITI DE 1ª QUALIDADE': { frequency: '-', weeklyConsumption: parseConsumption('8 unid.'), monthlyConsumption: parseConsumption('32 unid.') },
    'LINGUIÇA CALABRESA DEFUMADA (PREPARO)': { frequency: '1x/semana', weeklyConsumption: parseConsumption('220 g'), monthlyConsumption: parseConsumption('880 g') },
    'LINGUIÇA FRESCA FRANGO': { frequency: '1x/semana', weeklyConsumption: parseConsumption('720 g'), monthlyConsumption: parseConsumption('2.880 g') },
    'MACA GALA NACIONAL': { frequency: '3x/semana', weeklyConsumption: parseConsumption('1 unid.'), monthlyConsumption: parseConsumption('12 unid.') },
    'MAMÃO DE PRIMEIRA QUALIDADE': { frequency: '2x/semana', weeklyConsumption: parseConsumption('244 g'), monthlyConsumption: parseConsumption('976 g') },
    'MANGA': { frequency: '1x/semana', weeklyConsumption: parseConsumption('4 unid.'), monthlyConsumption: parseConsumption('16 unid.') },
    'MANTEIGA COM SAL': { frequency: '-', weeklyConsumption: parseConsumption('10 g'), monthlyConsumption: parseConsumption('40 g') },
    'MARACUJÁ AZEDO DE 1ª QUALIDADE': { frequency: '-', weeklyConsumption: parseConsumption('60 g'), monthlyConsumption: parseConsumption('240 g') },
    'MARGARINA VEGETAL': { frequency: '1x/dia', weeklyConsumption: parseConsumption('309 g'), monthlyConsumption: parseConsumption('1.236 g') },
    'MASSA ALIMENTÍCIA PARA SOPA': { frequency: '-', weeklyConsumption: parseConsumption('312 g'), monthlyConsumption: parseConsumption('1.248 g') },
    'MASSA ALIMENTÍCIA SECA (GUARNIÇÃO)': { frequency: '2x/semana', weeklyConsumption: parseConsumption('560 g'), monthlyConsumption: parseConsumption('2.240 g') },
    'MASSA ALIMENTÍCIA SECA (PRATO BASE)': { frequency: '1x/semana', weeklyConsumption: parseConsumption('480 g'), monthlyConsumption: parseConsumption('1.920 g') },
    'MASSA DE TOMATE TIPO: MOLHO PRONTO': { frequency: '-', weeklyConsumption: parseConsumption('200 g'), monthlyConsumption: parseConsumption('800 g') },
    'MASSA PARA LASANHA PRÉ-COZIDA': { frequency: '1x/quinzena', weeklyConsumption: parseConsumption('80 g'), monthlyConsumption: parseConsumption('320 g') },
    'MELANCIA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('2.600 g'), monthlyConsumption: parseConsumption('10.400 g') },
    'MELHORADOR TRIPLA AÇÃO': { frequency: 'Panificação', weeklyConsumption: parseConsumption('16 g'), monthlyConsumption: parseConsumption('64 g') },
    'MILHO DE CANJICA': { frequency: '1x/semana', weeklyConsumption: parseConsumption('124 g'), monthlyConsumption: parseConsumption('496 g') },
    'MISTURA ALIMENTÍCIA INGREDIENTES: FARINHA DE TRIGO': { frequency: '2x/dia', weeklyConsumption: parseConsumption('50 g'), monthlyConsumption: parseConsumption('200 g') },
    'MISTURA EM PÓ PARA GELATINA DIETÉTICA (SABORES DIVERSOS)': { frequency: '18x/mês', weeklyConsumption: parseConsumption('5,1 g'), monthlyConsumption: parseConsumption('20,4 g') },
    'MOLHO DE MESA TIPO: MAIONESE': { frequency: '1x/quinzena', weeklyConsumption: parseConsumption('30 g'), monthlyConsumption: parseConsumption('120 g') },
    'MOSTARDA (CONDIMENTO PREPARADO)': { frequency: '-', weeklyConsumption: parseConsumption('7 g'), monthlyConsumption: parseConsumption('28 g') },
    'OVO IN NATURA DE GALINHA BRANCO': { frequency: '2x/semana', weeklyConsumption: parseConsumption('8 unid.'), monthlyConsumption: parseConsumption('32 unid.') },
    'OVO IN NATURA DE GALINHA BRANCO MEDIO': { frequency: '2x/semana', weeklyConsumption: parseConsumption('8 unid.'), monthlyConsumption: parseConsumption('32 unid.') },
    'OVOS TIPO MÉDIO BRANCO': { frequency: '-', weeklyConsumption: parseConsumption('6 unid.'), monthlyConsumption: parseConsumption('24 unid.') },
    'PÃO FRANCÊS': { frequency: '2x/dia', weeklyConsumption: parseConsumption('3.060 g'), monthlyConsumption: parseConsumption('12.240 g') },
    'PÃO TIPO REDONDO SEM SAL': { frequency: '2x/dia', weeklyConsumption: parseConsumption('51 g'), monthlyConsumption: parseConsumption('204 g') },
    'PÉ SUÍNO SALGADO': { frequency: '1x/semana', weeklyConsumption: parseConsumption('204 g'), monthlyConsumption: parseConsumption('816 g') },
    'PEIXE EMPANADO': { frequency: '2x/semana', weeklyConsumption: parseConsumption('1.120 g'), monthlyConsumption: parseConsumption('4.480 g') },
    'PEIXE IN NATURA VARIEDADE: MERLUZA, TIPO CORTE: FILÉ': { frequency: '1x/semana', weeklyConsumption: parseConsumption('720 g'), monthlyConsumption: parseConsumption('2.880 g') },
    'PEIXE TIPO CAÇÃO (POSTA)': { frequency: '1x/semana', weeklyConsumption: parseConsumption('720 g'), monthlyConsumption: parseConsumption('2.880 g') },
    'PEIXE TIPO PESCADA BRANCA': { frequency: '1x/semana', weeklyConsumption: parseConsumption('720 g'), monthlyConsumption: parseConsumption('2.880 g') },
    'PEPINO COMUM': { frequency: '3x/semana', weeklyConsumption: parseConsumption('720 g'), monthlyConsumption: parseConsumption('2.880 g') },
    'PÊRA NACIONAL/ESTRANGEIRA DE 1ª QUALIDADE': { frequency: '2x/semana', weeklyConsumption: parseConsumption('1 unid.'), monthlyConsumption: parseConsumption('8 unid.') },
    'PESCADO EM CONSERVA ATUM': { frequency: '-', weeklyConsumption: parseConsumption('30 g'), monthlyConsumption: parseConsumption('120 g') },
    'PESCADO EM CONSERVA - SARDINHA': { frequency: '-', weeklyConsumption: parseConsumption('30 g'), monthlyConsumption: parseConsumption('120 g') },
    'PIMENTA VERMELHA PICANTE': { frequency: '-', weeklyConsumption: parseConsumption('2 g'), monthlyConsumption: parseConsumption('8 g') },
    'PIMENTÃO DE 1ª QUALIDADE': { frequency: '-', weeklyConsumption: parseConsumption('50 g'), monthlyConsumption: parseConsumption('200 g') },
    'PÓ PARA PREPARO DE PUDIM DIETÉTICO (SABORES DIVERSOS)': { frequency: '18x/mês', weeklyConsumption: parseConsumption('5,1 g'), monthlyConsumption: parseConsumption('20,4 g') },
    'PÓ PARA REFRESCO SABOR: TANGETINA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('160 g'), monthlyConsumption: parseConsumption('640 g') },
    'PÓ PUDIM SABOR: BAUNILHA': { frequency: '1x/semana', weeklyConsumption: parseConsumption('80 g'), monthlyConsumption: parseConsumption('320 g') },
    'POLVILHO AZEDO BRANCO': { frequency: '-', weeklyConsumption: parseConsumption('124 g'), monthlyConsumption: parseConsumption('496 g') },
    'POLVILHO DOCE BRANCO': { frequency: '-', weeklyConsumption: parseConsumption('124 g'), monthlyConsumption: parseConsumption('496 g') },
    'QUEIJO ORIGEM: DE VACA, VARIEDADE: MUÇARELA': { frequency: '1x/semana', weeklyConsumption: parseConsumption('104 g'), monthlyConsumption: parseConsumption('416 g') },
    'QUEIJO PARMESÃO': { frequency: '1x/semana', weeklyConsumption: parseConsumption('42,4 g'), monthlyConsumption: parseConsumption('169,6 g') },
    'QUEIJO PRATO': { frequency: '1x/semana', weeklyConsumption: parseConsumption('104 g'), monthlyConsumption: parseConsumption('416 g') },
    'QUEIJO TIPO MINAS FRESCAL SEM SAL': { frequency: '3x/semana', weeklyConsumption: parseConsumption('53 g'), monthlyConsumption: parseConsumption('212 g') },
    'QUEIJO TIPO RICOTA': { frequency: '1x/semana', weeklyConsumption: parseConsumption('53 g'), monthlyConsumption: parseConsumption('212 g') },
    'QUIABO': { frequency: '1x/semana', weeklyConsumption: parseConsumption('488 g'), monthlyConsumption: parseConsumption('1.952 g') },
    'RABANETE': { frequency: '1x/quinzena', weeklyConsumption: parseConsumption('100 g'), monthlyConsumption: parseConsumption('400 g') },
    'REFRIGERANTE TIPO COLA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('2.000 ml'), monthlyConsumption: parseConsumption('8.000 ml') },
    'REFRIGERANTE TIPO GUARANÁ': { frequency: '2x/semana', weeklyConsumption: parseConsumption('2.000 ml'), monthlyConsumption: parseConsumption('8.000 ml') },
    'REFRIGERANTE TIPO LARANJA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('2.000 ml'), monthlyConsumption: parseConsumption('8.000 ml') },
    'REPOLHO COZIDO': { frequency: '2x/semana', weeklyConsumption: parseConsumption('960 g'), monthlyConsumption: parseConsumption('3.840 g') },
    'REPOLHO VERDE': { frequency: '3x/semana', weeklyConsumption: parseConsumption('600 g'), monthlyConsumption: parseConsumption('2.400 g') },
    'SAGU': { frequency: '2x/semana', weeklyConsumption: parseConsumption('168 g'), monthlyConsumption: parseConsumption('672 g') },
    'SAL HIPOSSÓDICO EM SACHÊ': { frequency: '2x/dia', weeklyConsumption: parseConsumption('1 g'), monthlyConsumption: parseConsumption('4 g') },
    'SAL REFINADO EM SACHÊ': { frequency: '2x/dia', weeklyConsumption: parseConsumption('1 g'), monthlyConsumption: parseConsumption('4 g') },
    'SAL REFINADO IODADO': { frequency: 'Panificação', weeklyConsumption: parseConsumption('125 g'), monthlyConsumption: parseConsumption('500 g') },
    'SALSA (CHEIRO VERDE)': { frequency: '-', weeklyConsumption: parseConsumption('83 g'), monthlyConsumption: parseConsumption('332 g') },
    'SALSICHA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('960 g'), monthlyConsumption: parseConsumption('3.840 g') },
    'SALSICHA DE FRANGO': { frequency: '2x/semana', weeklyConsumption: parseConsumption('960 g'), monthlyConsumption: parseConsumption('3.840 g') },
    'SARDINHA CONGELADA (INTEIRA, SEM CABEÇA E EVISCERADA)': { frequency: '1x/semana', weeklyConsumption: parseConsumption('620 g'), monthlyConsumption: parseConsumption('2.480 g') },
    'SHOYU (MOLHO DE SOJA)': { frequency: '-', weeklyConsumption: parseConsumption('16 ml'), monthlyConsumption: parseConsumption('64 ml') },
    'SUCO APRESENTAÇÃO: PÓ, SABOR: UVA': { frequency: '2x/semana', weeklyConsumption: parseConsumption('160 g'), monthlyConsumption: parseConsumption('640 g') },
    'SUCO CONCENTRADO (GOIABA, MANGA, MARACUJÁ)': { frequency: '2x/semana', weeklyConsumption: parseConsumption('1.600 ml'), monthlyConsumption: parseConsumption('6.400 ml') },
    'TANGERINA CRAVO': { frequency: '1x/semana', weeklyConsumption: parseConsumption('4 unid.'), monthlyConsumption: parseConsumption('16 unid.') },
    'TANGERINA MURCOT': { frequency: '1x/semana', weeklyConsumption: parseConsumption('4 unid.'), monthlyConsumption: parseConsumption('16 unid.') },
    'TANGERINA PONKAN': { frequency: '1x/semana', weeklyConsumption: parseConsumption('4 unid.'), monthlyConsumption: parseConsumption('16 unid.') },
    'TEMPERO BAIANO': { frequency: '-', weeklyConsumption: parseConsumption('2 g'), monthlyConsumption: parseConsumption('8 g') },
    'TEMPERO TIPO: CALDO, APRESENTAÇÃO: PÓ, SABOR: CARNE': { frequency: '-', weeklyConsumption: parseConsumption('10,3 g'), monthlyConsumption: parseConsumption('41,2 g') },
    'TEMPERO TIPO: CALDO, APRESENTAÇÃO: PÓ, SABOR: GALINHA': { frequency: '-', weeklyConsumption: parseConsumption('10,3 g'), monthlyConsumption: parseConsumption('41,2 g') },
    'TOMATE LONGA VIDA': { frequency: '5x/semana', weeklyConsumption: parseConsumption('2.200 g'), monthlyConsumption: parseConsumption('8.800 g') },
    'TOMATE MADURO DE 1ª QUALIDADE': { frequency: '15x/mês', weeklyConsumption: parseConsumption('1.065 g'), monthlyConsumption: parseConsumption('4.260 g') },
    'TOMATE SANTA CRUZ': { frequency: '15x/mês', weeklyConsumption: parseConsumption('1.065 g'), monthlyConsumption: parseConsumption('4.260 g') },
    'TRIGO PARA QUIBE': { frequency: '-', weeklyConsumption: parseConsumption('20 g'), monthlyConsumption: parseConsumption('80 g') },
    'UVA NIÁGARA': { frequency: '2x/ano', weeklyConsumption: parseConsumption('40 g/mês'), monthlyConsumption: parseConsumption('160 g') },
    'VAGEM': { frequency: '1x/semana', weeklyConsumption: parseConsumption('440 g'), monthlyConsumption: parseConsumption('1.760 g') },
    'XAROPE DE GROSELHA': { frequency: '-', weeklyConsumption: parseConsumption('94 ml'), monthlyConsumption: parseConsumption('376 ml') },
};